### ISSUE TITLE
Trouble Installing pbccs through pitchfork

### ISSUE THREAD

**Issue by MerillaM** [PacificBiosciences/pitchfork#417]
Hi!

I've been trying to install pbccs through pitchfork, and am running into problems when the installation begins working through unanimity. The last lines before the fatal error messages are following:

`make[4]: Entering directory '/opt/pitchfork/workspace/unanimity/_build'
make[4]: Leaving directory '/opt/pitchfork/workspace/unanimity/_build'
make[4]: Entering directory '/opt/pitchfork/workspace/unanimity/_build'
[ 24%] Building CXX object src/CMakeFiles/cc2.dir/models/S_P2C2v5_Model.cpp.o`

Then, the fatal errors:

`In file included from /opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h:45:0,
                 from /opt/pitchfork/workspace/unanimity/include/pacbio/consensus/ModelConfig.h:52,
                 from /opt/pitchfork/workspace/unanimity/src/models/S_P2C2v5_Model.cpp:46:
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/ConversionFunctions.h: In function ‘constexpr uint8_t PacBio::Data::detail::{anonymous}::ASCIIToNCBI4naImpl(char, bool)’:
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/ConversionFunctions.h:132:1: error: expression ‘<throw-expression>’ is not a constant-expression
 }
 ^
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/ConversionFunctions.h: In function ‘constexpr uint8_t PacBio::Data::detail::{anonymous}::NCBI4naToNCBI2naImpl(uint8_t)’:
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/ConversionFunctions.h:175:1: error: expression ‘<throw-expression>’ is not a constant-expression
 }
 ^
In file included from /opt/pitchfork/workspace/unanimity/include/pacbio/consensus/ModelConfig.h:52:0,
                 from /opt/pitchfork/workspace/unanimity/src/models/S_P2C2v5_Model.cpp:46:
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h: At global scope:
/opt/pitchfork/workspace/unanimity/src/models/../Recursor.h:196:29:   in constexpr expansion of ‘PacBio::Data::detail::NCBI4na::FromASCII(65, 1)’
/opt/pitchfork/workspace/unanimity/src/models/../Recursor.h:196:29:   in constexpr expansion of ‘PacBio::Data::detail::NCBI4na(((int)base), ((int)checkValid))’
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h:196:35: error: ‘constexpr uint8_t PacBio::Data::detail::{anonymous}::ASCIIToNCBI4naImpl(char, bool)’ called in a constant expression
         : data_{ASCIIToNCBI4naImpl(base, checkValid)}
                                   ^
/opt/pitchfork/workspace/unanimity/src/models/../Recursor.h:197:90:   in constexpr expansion of ‘PacBio::Consensus::TemplatePosition(65, 1.0e+0, 0.0, 0.0, 0.0)’
/opt/pitchfork/workspace/unanimity/include/pacbio/consensus/ModelConfig.h:89:40:   in constexpr expansion of ‘PacBio::Data::detail::NCBI4na::FromASCII(((int)((PacBio::Consensus::TemplatePosition*)this)->PacBio::Consensus::TemplatePosition::Base), 1)’
/opt/pitchfork/workspace/unanimity/src/models/../Recursor.h:197:90:   in constexpr expansion of ‘PacBio::Data::detail::NCBI4na(((int)base), ((int)checkValid))’
/opt/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h:196:35: error: ‘constexpr uint8_t PacBio::Data::detail::{anonymous}::ASCIIToNCBI4naImpl(char, bool)’ called in a constant expression
In file included from /opt/pitchfork/workspace/unanimity/src/models/S_P2C2v5_Model.cpp:54:0:
/opt/pitchfork/workspace/unanimity/src/models/HelperFunctions.h: In function ‘constexpr uint8_t PacBio::Consensus::{anonymous}::EncodeBase(char)’:
/opt/pitchfork/workspace/unanimity/src/models/HelperFunctions.h:88:1: error: expression ‘<throw-expression>’ is not a constant-expression
 }
 ^
/opt/pitchfork/workspace/unanimity/src/models/HelperFunctions.h: In function ‘constexpr uint8_t PacBio::Consensus::{anonymous}::EncodeBase(char, uint8_t)’:
/opt/pitchfork/workspace/unanimity/src/models/HelperFunctions.h:105:1: error: expression ‘<throw-expression>’ is not a constant-expression
 }
 ^
/opt/pitchfork/workspace/unanimity/src/models/HelperFunctions.h: In function ‘constexpr std::pair<char, unsigned char> PacBio::Consensus::{anonymous}::DecodeEmission(uint8_t)’:
/opt/pitchfork/workspace/unanimity/src/models/HelperFunctions.h:130:1: error: expression ‘<throw-expression>’ is not a constant-expression
 }
 ^
src/CMakeFiles/cc2.dir/build.make:326: recipe for target 'src/CMakeFiles/cc2.dir/models/S_P2C2v5_Model.cpp.o' failed
make[4]: *** [src/CMakeFiles/cc2.dir/models/S_P2C2v5_Model.cpp.o] Error 1
make[4]: Leaving directory '/opt/pitchfork/workspace/unanimity/_build'
CMakeFiles/Makefile2:129: recipe for target 'src/CMakeFiles/cc2.dir/all' failed
make[3]: *** [src/CMakeFiles/cc2.dir/all] Error 2
make[3]: Leaving directory '/opt/pitchfork/workspace/unanimity/_build'
Makefile:127: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/opt/pitchfork/workspace/unanimity/_build'
Makefile:48: recipe for target '/opt/pitchfork/workspace/unanimity/_build/ccs' failed
make[1]: *** [/opt/pitchfork/workspace/unanimity/_build/ccs] Error 2
make[1]: Leaving directory '/opt/pitchfork/ports/pacbio/unanimity'
Makefile:402: recipe for target 'unanimity' failed
make: *** [unanimity] Error 2`

Anyone have an idea on how to fix this? 
I'm running Ubuntu 16.04.3, gcc version 6.4.

**Comment by mhsieh** [comment]
I will take a look.

**Comment by mhsieh** [comment]
Dear Merilla,
   Can you run this command and see if you have more recent copy of the unanimity?
```
git -C /opt/pitchfork/workspace/unanimity rev-parse --short HEAD
```

I tried to compile it in my own ubuntu16 box and it passed.

**Comment by MerillaM** [comment]
My output from that command is: fb25df6

**Comment by mhsieh** [comment]
This version of unanimity works fine in my ubuntu 16.04.3, can you share with me how did you install the gcc6? Thanks/

**Comment by MerillaM** [comment]
sudo apt install gcc-6

**Comment by mhsieh** [comment]
It only gives you gcc-6.3, right? But even gcc-6.3 should let you finish the compilation (after you modify the checkCC.) is this pitchfork a new clone or did you previously work on this pitchfork folder before?

**Comment by MerillaM** [comment]
My gcc version currently is 6.4. This is a new clone of pitchfork

**Comment by MerillaM** [comment]
How/to what would I modify the checkCC?

**Comment by mhsieh** [comment]
interesting i thought ubuntu 16 only provides gcc-6.3.

**Comment by mhsieh** [comment]
Did you use this ppa? ppa:jonathonf/gcc-6.4

**Comment by MerillaM** [comment]
Yes, I did

**Comment by mhsieh** [comment]
That was not very official, but I will try to reproduce.

**Comment by MerillaM** [comment]
Ok, thank you!

**Comment by mhsieh** [comment]
Dear Merilla,
    Even more interestingly I was able to compile it without problem. Can you show me the out put of your `gcc --version` ?

It probably should be:
```
gcc (Ubuntu 6.4.0-10ubuntu1~16.04.york0) 6.4.0 20171112
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by mhsieh** [comment]
and also let me know if you modified settings.mk file

**Comment by SoapZA** [comment]
Hi @MerillaM, have you overridden `CC` and `CXX` to use GCC 6? Ubuntu 16.04 uses GCC 5.3.1 by default. If need be, we can look into making the throw conditional compiler dependent.

**Comment by MerillaM** [comment]
@mhsieh My output is the same as what you listened. I didn't modify anything in the settings.mk file.

@SoapZA How would I go about overriding those?

**Comment by mhsieh** [comment]
Judging from Merilla's reply, she likely did change the default gcc with update-alternatives command.
If that's case, I would not have any idea why your compiler is complaining as if it's gcc5.

@MerillaM , can you also send us the output of these two commands?
`type gcc` `which gcc`

Thanks

**Comment by MerillaM** [comment]
Correct, @mhsieh 

The output:

`gcc is hashed (/usr/bin/gcc)
which is /usr/bin/which
gcc is hashed (/usr/bin/gcc)`

**Comment by mhsieh** [comment]
Now I am stumped, your gcc6 hates c++14, which shouldn't happen. @MerillaM , let me know if you have a deadline, if you do, I can send you a link to my built artifact.

**Comment by MerillaM** [comment]
Just so you know what I did before, this was my series of steps to install pbccs. Anything look wrong with this?

`sudo git clone git://github.com/PacificBiosciences/pitchfork` 
`cd pitchfork`
`sudo make pbccs`

I have an unofficial deadline by the end of this week.

**Comment by mhsieh** [comment]
Please do not do `sudo` since root might have its alternative.
What I might do in your case: 
```
cd $HOME
git clone git://github.com/PacificBiosciences/pitchfork
sudo mv pitchfork /opt/
cd /opt/pitchfork
make pbccs
```
I will be working on the prebuilt for you

**Comment by MerillaM** [comment]
Got it -- thank you! I will continue to play around with this, and let you know if there is any change.

**Comment by mhsieh** [comment]
https://www.dropbox.com/s/9pguez5b00zbaik/pbccs.tgz?dl=0

**Comment by mhsieh** [comment]
If pbccs indeed was the only port that breaks, that prebuilt should work. Please let me know after you finished the download.

**Comment by MerillaM** [comment]
@mhsieh Thank you very much :)

**Comment by mhsieh** [comment]
Do note that we don't really test anything on ubuntu16 but we are still very interested in any compatibility issue anyway.

**Comment by MerillaM** [comment]
Unfortunately, I am getting the same error message.

**Comment by mhsieh** [comment]
you probably untar-ed it to the wrong place since 1. you don't have to do `make pbccs` 2. even if you did, make should consider that it's already done and do nothing.

**Comment by SoapZA** [comment]
Hi @MerillaM 
I've added compatibility shims to pbccs/unanimity so that it builds with GCC 4.9 and 5 (https://github.com/PacificBiosciences/unanimity/commit/0758688f9376c8488f996069f3fd35e62f85c9da). Please give it a try and see if you can build our software using pitchfork with these changes.

**Comment by MerillaM** [comment]
The error I am getting is now this:

`[ 95%] Linking CXX executable ../arrow
/usr/bin/ld: /opt/pitchfork/deployment/lib/libpbcopper.a(Logging.cpp.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/CMakeFiles/arrow.dir/build.make:100: recipe for target 'arrow' failed
make[4]: *** [arrow] Error 1
make[4]: Leaving directory '/opt/pitchfork/workspace/unanimity/_build'
CMakeFiles/Makefile2:92: recipe for target 'src/CMakeFiles/arrow.dir/all' failed
make[3]: *** [src/CMakeFiles/arrow.dir/all] Error 2
make[3]: Leaving directory '/opt/pitchfork/workspace/unanimity/_build'
Makefile:127: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/opt/pitchfork/workspace/unanimity/_build'
Makefile:48: recipe for target '/opt/pitchfork/workspace/unanimity/_build/ccs' failed
make[1]: *** [/opt/pitchfork/workspace/unanimity/_build/ccs] Error 2
make[1]: Leaving directory '/opt/pitchfork/ports/pacbio/unanimity'
Makefile:402: recipe for target 'unanimity' failed
make: *** [unanimity] Error 2`

@mhsieh : I untared into /opt/pitchfork/deployment. Is this correct?

**Comment by mhsieh** [comment]
@MerillaM sorry I missed the notification, the github probably hates me. I think my artifact was missing a file, that's why you still got into the building part of it.

The other problem was that my compiler might have been using a custom libc, I will give you a new version of the tarball as well.

**Comment by mhsieh** [comment]
try again https://www.dropbox.com/s/9pguez5b00zbaik/pbccs.tgz?dl=0

**Comment by MerillaM** [comment]
@mhsieh This worked! Thank you so much for all of your help.

**Comment by MerillaM** [comment]
I'm now running into problems running ccs.

I input:
`ccs --minLength=100 myCCS.bam m54071_170630_031403.subreads.bam`

My error message is:
`ccs: error while loading shared libraries: libpbbam.so: cannot open shared object file: No such file or directory`

**Comment by mhsieh** [comment]
did you load the setup-env.sh ?

one way to have an isolated bash session with the environment is to do
```
bash --init-file /opt/pitchfork/deployment/setup-env.sh
```
So when you exit that bash, pitchfork won't contaminate your environment.

**Comment by MerillaM** [comment]
That did the trick -- thanks again!

**Comment by mhsieh** [comment]
if you want to use it in your random script, try writing a wrapper shell script for ccs like this.
```
#!/bin/bash -e
source /opt/pitchfork/setup-env.sh
exec ccs "$@"
```

**Comment by mhsieh** [comment]
pbccs is also now available on bioconda - https://bioconda.github.io/recipes/pbccs/README.html
